### ISSUE TITLE
Error in loop while loading

### ISSUE THREAD

**Issue by xitianllc** [tableau/extension-date-updater#26]
We are seeing an issue in Tableau server 2019.4.1 where this extension get into an endless loop when trying to load. It appears to get an http 401 (Unauthorized) error when posting to the command: save-add-in-settings
![screenshot](https://user-images.githubusercontent.com/60196560/72927502-586ee100-3d24-11ea-8058-d0a6569ca2ac.png)

**Comment by KeshiaRose** [comment]
Hi @xitianllc,

Are you using the latest version of the extension? I did a fix for the save-settings issue in November. It was happening when Viewers accessed the dashboard. You should have received the update automatically unless perhaps you made a local copy?

However, that being said, if your Viewers do not have permission to download summary data, you will still get this issue anyways, even with the latest extension version. However, you will see the error coming from the get-parameters command instead. This is because we have a bug with permissions that refreshes the dashboard and there is no way to stop it from within the extension code. 

If you want it to work for Viewers, they will need to have permission to download summary data. We're currently working on a fix for the refreshing otherwise, but not sure about when we will get out an update.

Take care,
Keshia
